### PR TITLE
Implement state verification and allow to pass nonce and prompt through the client

### PR DESCRIPTION
**Pull request by timhallmann**

### CODE REVIEW

**Comment by timhallmann** [comment]
I think I'm done making mistakes for the moment. Sorry about the noise.

**Comment by ftsell** [comment]
> I think I'm done making mistakes for the moment, should be safe to review now. Sorry about the noise.

Well, almost :)

**Comment by timhallmann** [comment]
I forgot to add a comment but I've fixed the formatting. Mind approving the workflow yet another time? :)

**Review by ftsell — APPROVED** [review]
thanks for the contribution

**Pull request merged**
